### ISSUE TITLE
Can you also add a beginner's guide to emacs ?

### ISSUE THREAD

**Issue by kiranruth** [ChillarAnand/emacsism#5]

**Comment by ChillarAnand** [comment]
This short guide was meant only to provide a glimpse of emacs editing features. 

However, we can add a list of curated resources that will be useful for beginners.

**Comment by kiranruth** [comment]
Thanks For the update @ChillarAnand. Eagerly awaiting for the resource.

**Comment by ChillarAnand** [comment]
Beginners tutorials:

Peep code tutorial https://www.youtube.com/watch?v=CziEHzO5cPI
http://www.jesshamrick.com/2012/09/10/absolute-beginners-guide-to-emacs/


Useful resources:
http://emacsrocks.com/
https://www.emacswiki.org/emacs/EmacsScreencasts

Python emacs
https://github.com/jorgenschaefer/elpy
http://chillaranand.github.io/emacs-py-ide/
